/**
 * /v1/buy-approve/:token — public approval endpoint (Epic 88, MCP UI).
 *
 * No authentication: the magic token IS the authorization. Single-use,
 * bound to a specific approval, generated by /v1/buy when the policy
 * fires. Used by the inline approval UI rendered inside Claude (MCP App
 * extension) so the user can approve without leaving the chat.
 *
 * Flow:
 *   POST /v1/buy-approve/:token
 *     1. Look up the approval row whose payment_context.approve_token == token
 *     2. Reject if approval is not pending or token already consumed
 *     3. Mark approval approved (decided_by = approval's customer_id)
 *     4. Re-call ACP completion with the bound wallet_payment_method_id
 *        — this charges the user's saved card via Stripe
 *     5. Mark approval executed
 *     6. Return a small HTML success page (so when the form submits in
 *        Claude's iframe, the user sees a green confirmation inline)
 *
 *   GET /v1/buy-approve/:token  → returns the same UI page (idempotent
 *     status view; useful if the iframe reloads after approval)
 */

import { Hono } from 'hono';
import { createClient } from '../db/client.js';
import { getStripeClient, isStripeConfigured } from '../services/stripe/index.js';

const app = new Hono();

// ─────────────────────────────────────────────────────────────────────
// Helpers — render the small success / failure / pending HTML pages.
// Self-contained, no external CSS, theme-aware via prefers-color-scheme.
// ─────────────────────────────────────────────────────────────────────

function htmlShell(body: string, title = 'Sly approval') {
  return `<!doctype html><html><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>${title}</title>
<style>
  :root { color-scheme: light dark; }
  html, body { margin:0; padding:0; height:100%; background:#0f172a; color:#e2e8f0; font-family: -apple-system, BlinkMacSystemFont, "SF Pro", system-ui, sans-serif; }
  @media (prefers-color-scheme: light) { html, body { background:#f8fafc; color:#0f172a; } }
  .wrap { padding:24px; max-width:480px; margin:0 auto; }
  .card { background:#1e293b; border:1px solid #334155; border-radius:16px; padding:20px; margin-bottom:12px; }
  @media (prefers-color-scheme: light) { .card { background:#fff; border-color:#e2e8f0; } }
  .accent-green { border-color:#10b981; }
  .accent-rose  { border-color:#f43f5e; }
  .row { display:flex; align-items:center; gap:12px; }
  .badge { display:inline-flex; width:40px; height:40px; align-items:center; justify-content:center; border-radius:9999px; font-size:20px; }
  .badge-green { background:rgba(16,185,129,0.15); color:#10b981; }
  .badge-rose  { background:rgba(244,63,94,0.15);  color:#f43f5e; }
  .muted { opacity:.7; font-size:13px; }
  .total { font-size:28px; font-weight:600; }
</style></head><body><div class="wrap">${body}</div></body></html>`;
}

function successHtml(opts: { merchant: string; total: number; currency: string; brand?: string | null; last4?: string | null; piId?: string | null }) {
  // Optional STRIPE_ACCOUNT_ID prefix lands the user in the correct
  // Stripe account directly — without it Stripe routes to whichever
  // account the user's browser is already signed into.
  const stripeAcct = process.env.STRIPE_ACCOUNT_ID || '';
  const stripeBase = `https://dashboard.stripe.com${stripeAcct ? '/' + stripeAcct : ''}/test/payments`;
  const stripeLink = opts.piId
    ? `<a href="${stripeBase}/${opts.piId}" target="_blank" rel="noopener" style="display:inline-block;margin-top:12px;padding:8px 14px;border-radius:8px;background:#635bff;color:#fff;text-decoration:none;font-size:13px;font-weight:500">View on Stripe →</a>`
    : '';
  return htmlShell(`
    <div class="card accent-green">
      <div class="row">
        <div class="badge badge-green">✓</div>
        <div>
          <div style="font-weight:600">Approved · order placed</div>
          <div class="muted">${opts.merchant}</div>
        </div>
      </div>
      <div style="margin-top:14px" class="total">${opts.currency} ${opts.total.toFixed(2)}</div>
      <div class="muted" style="margin-top:4px">Charged to ${opts.brand ?? 'card'} •••• ${opts.last4 ?? '••••'}</div>
      ${opts.piId ? `<div class="muted" style="margin-top:8px;font-family:ui-monospace,monospace;font-size:11px">${opts.piId}</div>` : ''}
      ${stripeLink}
    </div>
  `, 'Approved');
}

function errorHtml(message: string) {
  return htmlShell(`
    <div class="card accent-rose">
      <div class="row">
        <div class="badge badge-rose">!</div>
        <div>
          <div style="font-weight:600">Couldn't approve</div>
          <div class="muted">${message}</div>
        </div>
      </div>
    </div>
  `, 'Approval failed');
}

// ─────────────────────────────────────────────────────────────────────
// Approve handler — same logic on POST (form submit) and GET (idempotent)
// ─────────────────────────────────────────────────────────────────────

async function handleApproveByToken(c: any, token: string) {
  const supabase: any = createClient();

  // Find the approval whose payment_context.approve_token matches.
  // We use `payment_context->>approve_token` for the match.
  const { data: approval } = await supabase
    .from('agent_payment_approvals')
    .select('id, status, tenant_id, wallet_id, agent_id, amount, currency, payment_context, recipient, executed_transfer_id')
    .eq('payment_context->>approve_token', token)
    .maybeSingle();

  if (!approval) {
    return c.html(errorHtml('Link is invalid or has been used. Please request a new one.'), 404);
  }

  // Already executed — show the receipt as if just approved.
  if (approval.status === 'executed') {
    const ctxItems = approval.payment_context;
    return c.html(successHtml({
      merchant: approval.recipient?.merchant_name || ctxItems?.merchant_name || 'Merchant',
      total: parseFloat(approval.amount as any),
      currency: approval.currency,
      brand: ctxItems?.card_brand ?? null,
      last4: ctxItems?.card_last4 ?? null,
      piId: ctxItems?.stripe_payment_intent_id ?? null,
    }));
  }

  if (approval.status === 'rejected') {
    return c.html(errorHtml('This order was previously denied.'), 400);
  }
  if (approval.status === 'expired') {
    return c.html(errorHtml('Approval link has expired. Please ask your agent to start a new order.'), 410);
  }
  if (approval.status !== 'pending' && approval.status !== 'approved') {
    return c.html(errorHtml(`Unexpected approval state: ${approval.status}`), 400);
  }

  // Resolve buyer (for decided_by FK) — payment_context.buyer_user_id was set
  // by /v1/buy. Fall back to the tenant owner if missing.
  let decidedBy: string | null = approval.payment_context?.buyer_user_id || null;
  if (!decidedBy) {
    const { data: owner } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('tenant_id', approval.tenant_id)
      .eq('role', 'owner')
      .maybeSingle();
    decidedBy = owner?.id ?? null;
  }
  if (!decidedBy) {
    return c.html(errorHtml('No buyer profile bound to this approval.'), 500);
  }

  // 1) Approve the row.
  await supabase
    .from('agent_payment_approvals')
    .update({
      status: 'approved',
      decided_by: decidedBy,
      decided_at: new Date().toISOString(),
      decision_reason: 'inline mcp-app approval',
    })
    .eq('id', approval.id);

  // 2) Charge the saved card directly. (Mirror the ACP card-path logic.)
  if (!isStripeConfigured()) {
    return c.html(errorHtml('Stripe is not configured.'), 503);
  }
  const ctxData = approval.payment_context || {};
  const checkoutUuid = ctxData.checkout_uuid as string | undefined;
  const walletPmId = ctxData.wallet_payment_method_id as string | undefined;
  if (!checkoutUuid || !walletPmId) {
    return c.html(errorHtml('Missing payment context — cannot charge card.'), 500);
  }

  // Look up the saved card row.
  const { data: card } = await supabase
    .from('wallet_payment_methods')
    .select('id, brand, last4, stripe_customer_id, stripe_payment_method_id')
    .eq('id', walletPmId)
    .is('detached_at', null)
    .maybeSingle();
  if (!card) {
    return c.html(errorHtml('Saved card not found or removed since approval was created.'), 400);
  }

  // Look up the checkout for amount + merchant resolution.
  const { data: checkout } = await supabase
    .from('acp_checkouts')
    .select('id, total_amount, currency, merchant_id, merchant_name, merchant_account_id, account_id')
    .eq('id', checkoutUuid)
    .maybeSingle();
  if (!checkout) {
    return c.html(errorHtml('Underlying checkout missing — cannot charge.'), 500);
  }

  const total = parseFloat(checkout.total_amount as any);
  const currency = checkout.currency || 'USD';

  // Charge.
  const stripe = getStripeClient();
  let pi: any;
  try {
    pi = await stripe.createPaymentIntent({
      amount: Math.round(total * 100),
      currency: currency === 'USDC' ? 'usd' : currency.toLowerCase(),
      customerId: card.stripe_customer_id,
      paymentMethodId: card.stripe_payment_method_id,
      confirm: true,
      offSession: true,
      description: `Sly checkout: ${checkout.merchant_name || checkout.merchant_id}`,
      metadata: {
        checkout_id: ctxData.checkout_id || '',
        payos_checkout_uuid: checkout.id,
        merchant_id: checkout.merchant_id || '',
        agent_id: approval.agent_id || '',
        wallet_payment_method_id: card.id,
        sly_user_id: decidedBy,
        source: 'sly_buy_inline_approve',
      },
      idempotencyKey: `inline-approve-${approval.id}`,
    });
  } catch (err: any) {
    console.error('[buy-approve-public] PaymentIntent failed:', err.message);
    await supabase
      .from('agent_payment_approvals')
      .update({ execution_error: err.message })
      .eq('id', approval.id);
    return c.html(errorHtml(`Card charge failed: ${err.message}`), 402);
  }

  // 3) Record transfer + update checkout.
  const { data: transfer } = await supabase
    .from('transfers')
    .insert({
      tenant_id: approval.tenant_id,
      environment: 'test',
      from_account_id: checkout.account_id,
      to_account_id: checkout.merchant_account_id || checkout.account_id,
      amount: total,
      currency,
      type: 'acp',
      status: 'completed',
      description: `Sly checkout: ${checkout.merchant_name} (card ${card.brand} ${card.last4})`,
      protocol_metadata: {
        protocol: 'acp',
        source: 'sly_buy_inline_approve',
        checkout_id: ctxData.checkout_id,
        merchant_id: checkout.merchant_id,
        merchant_account_id: checkout.merchant_account_id,
        merchant_name: checkout.merchant_name,
        agent_id: approval.agent_id,
        wallet_payment_method_id: card.id,
        stripe_payment_intent_id: pi.id,
        stripe_payment_method: card.stripe_payment_method_id,
        card_brand: card.brand,
        card_last4: card.last4,
      },
      initiated_by_type: 'user',
      initiated_by_id: decidedBy,
      initiated_by_name: 'inline approval',
    })
    .select()
    .single();

  await supabase
    .from('acp_checkouts')
    .update({
      status: 'completed',
      transfer_id: transfer?.id || null,
      payment_method: 'card',
      completed_at: new Date().toISOString(),
      checkout_data: {
        source: 'sly_buy_inline_approve',
        stripe_payment_intent_id: pi.id,
        stripe_payment_status: pi.status,
        card_brand: card.brand,
        card_last4: card.last4,
      },
    })
    .eq('id', checkout.id);

  // 4) Mark approval executed and stash receipt fields in payment_context
  // so subsequent GETs render the same success page.
  await supabase
    .from('agent_payment_approvals')
    .update({
      status: 'executed',
      executed_transfer_id: transfer?.id || null,
      executed_at: new Date().toISOString(),
      payment_context: {
        ...ctxData,
        stripe_payment_intent_id: pi.id,
        card_brand: card.brand,
        card_last4: card.last4,
        merchant_name: checkout.merchant_name,
      },
    })
    .eq('id', approval.id);

  return c.html(successHtml({
    merchant: checkout.merchant_name || 'Merchant',
    total,
    currency,
    brand: card.brand,
    last4: card.last4,
    piId: pi.id,
  }));
}

/**
 * GET /v1/buy-approve/:token/info — public, no auth.
 * Returns approval summary + a fresh Stripe PaymentIntent client_secret
 * so the guest-checkout page can mount Stripe Payment Element and let
 * the user enter a card directly. The PaymentIntent is created with
 * setup_future_usage: 'off_session' so we can also vault the card if
 * the user opts in via the "save for next time" checkbox post-pay.
 */
app.get('/:token/info', async (c) => {
  const token = c.req.param('token');
  const supabase: any = createClient();

  const { data: approval } = await supabase
    .from('agent_payment_approvals')
    .select('id, status, tenant_id, agent_id, amount, currency, payment_context, recipient, executed_transfer_id')
    .eq('payment_context->>approve_token', token)
    .maybeSingle();
  if (!approval) return c.json({ error: 'Link is invalid or expired.' }, 404);

  const ctxData = approval.payment_context || {};
  const recipient = approval.recipient || {};

  // Resolve agent name
  let agentName = 'your agent';
  if (approval.agent_id) {
    const { data: agent } = await supabase.from('agents').select('name').eq('id', approval.agent_id).maybeSingle();
    if (agent?.name) agentName = agent.name;
  }

  // If already executed, return the receipt fields and stop.
  if (approval.status === 'executed') {
    return c.json({
      status: 'executed',
      merchant: recipient.merchant_name || ctxData.merchant_name,
      total: parseFloat(approval.amount as any),
      currency: approval.currency,
      items: ctxData.items || [],
      agent: agentName,
      receipt: {
        stripe_payment_intent_id: ctxData.stripe_payment_intent_id ?? null,
        card_brand: ctxData.card_brand ?? null,
        card_last4: ctxData.card_last4 ?? null,
      },
    });
  }
  if (approval.status === 'rejected') return c.json({ status: 'rejected' });
  if (approval.status === 'expired') return c.json({ status: 'expired' });

  // Not yet executed — mint a fresh PaymentIntent client_secret for the
  // guest checkout. We only mint once: cache the PaymentIntent id on
  // payment_context.guest_payment_intent_id so refreshes return the same.
  if (!isStripeConfigured()) return c.json({ error: 'Stripe not configured' }, 503);
  const stripe = getStripeClient();

  // Look up the buyer (for setup_future_usage and metadata)
  const buyerUserId: string | null = ctxData.buyer_user_id || null;
  let stripeCustomerId: string | null = null;
  if (buyerUserId) {
    const { data: cust } = await supabase
      .from('wallet_stripe_customers')
      .select('stripe_customer_id')
      .eq('user_id', buyerUserId)
      .maybeSingle();
    stripeCustomerId = cust?.stripe_customer_id || null;
  }

  // Reuse cached PI if present.
  let pi: any = null;
  if (ctxData.guest_payment_intent_id) {
    try {
      pi = await stripe.getPaymentIntent(ctxData.guest_payment_intent_id);
      // If the PI is in a final/non-confirmable state, ignore and remint.
      if (!['requires_payment_method', 'requires_confirmation', 'requires_action'].includes(pi.status)) {
        pi = null;
      }
    } catch {
      pi = null;
    }
  }

  if (!pi) {
    pi = await stripe.createPaymentIntent({
      amount: Math.round(parseFloat(approval.amount as any) * 100),
      currency: (approval.currency === 'USDC' || !approval.currency) ? 'usd' : (approval.currency as string).toLowerCase(),
      customerId: stripeCustomerId || undefined,
      // Force card-only — Link auto-prompts on familiar emails and saves
      // a type='link' method we don't render. Cleaner demo UX without it.
      paymentMethodTypes: ['card'],
      description: `Sly checkout: ${recipient.merchant_name || ctxData.merchant_name || 'merchant'}`,
      metadata: {
        sly_approval_token: token,
        approval_id: approval.id,
        merchant_id: ctxData.merchant_id ?? '',
        merchant_name: recipient.merchant_name ?? ctxData.merchant_name ?? '',
        agent_id: approval.agent_id ?? '',
        sly_user_id: buyerUserId ?? '',
        source: 'sly_buy_guest',
      },
      idempotencyKey: `guest-pi-${approval.id}`,
    });

    // Persist the PI id back onto payment_context for idempotent reloads.
    await supabase
      .from('agent_payment_approvals')
      .update({
        payment_context: { ...ctxData, guest_payment_intent_id: pi.id },
      })
      .eq('id', approval.id);
  }

  return c.json({
    status: 'awaiting_payment',
    merchant: recipient.merchant_name || ctxData.merchant_name,
    total: parseFloat(approval.amount as any),
    currency: approval.currency,
    items: ctxData.items || [],
    agent: agentName,
    reason: ctxData.reason ?? null,
    publishable_key: process.env.STRIPE_PUBLISHABLE_KEY,
    payment_intent_client_secret: pi.client_secret,
  });
});

/**
 * POST /v1/buy-approve/:token/finalize — public, no auth.
 * Called by the guest-checkout page after Stripe.js confirms the
 * PaymentIntent. We re-fetch the PI to verify status === 'succeeded'
 * (never trust the client), then mark approval executed and create
 * the transfer / update the checkout. Idempotent.
 */
app.post('/:token/finalize', async (c) => {
  const token = c.req.param('token');
  const body = await c.req.json().catch(() => ({}));
  const piIdFromClient = (body as any).payment_intent_id as string | undefined;

  const supabase: any = createClient();
  const { data: approval } = await supabase
    .from('agent_payment_approvals')
    .select('id, status, tenant_id, wallet_id, agent_id, amount, currency, payment_context, recipient')
    .eq('payment_context->>approve_token', token)
    .maybeSingle();
  if (!approval) return c.json({ error: 'Link is invalid or expired.' }, 404);
  if (approval.status === 'executed') {
    return c.json({ status: 'completed', already_done: true });
  }
  if (approval.status === 'rejected' || approval.status === 'expired') {
    return c.json({ error: `Approval is in ${approval.status} state` }, 400);
  }

  const ctxData = approval.payment_context || {};
  const piId = piIdFromClient || ctxData.guest_payment_intent_id;
  if (!piId) return c.json({ error: 'No PaymentIntent found for this approval.' }, 400);

  if (!isStripeConfigured()) return c.json({ error: 'Stripe not configured' }, 503);
  const stripe = getStripeClient();

  // Verify the PI is actually paid. Don't trust client.
  const pi = await stripe.getPaymentIntent(piId);
  if (pi.status !== 'succeeded') {
    return c.json({
      error: `PaymentIntent not succeeded (status: ${pi.status}). Try again.`,
      pi_status: pi.status,
    }, 402);
  }
  const piPayload: any = pi as any;

  // Resolve buyer and merchant for transfer ownership.
  let decidedBy: string | null = ctxData.buyer_user_id || null;
  if (!decidedBy) {
    const { data: owner } = await supabase
      .from('user_profiles')
      .select('id')
      .eq('tenant_id', approval.tenant_id)
      .eq('role', 'owner')
      .maybeSingle();
    decidedBy = owner?.id || null;
  }

  // Pull the underlying ACP checkout for routing.
  const checkoutUuid = ctxData.checkout_uuid;
  const { data: checkout } = await supabase
    .from('acp_checkouts')
    .select('id, total_amount, currency, merchant_id, merchant_name, merchant_account_id, account_id')
    .eq('id', checkoutUuid)
    .maybeSingle();
  if (!checkout) return c.json({ error: 'Underlying checkout missing' }, 500);

  // Card details from the PaymentIntent (Stripe returns the latest charge
  // with payment_method_details when expanded; we'll fetch the PM if not).
  let cardBrand: string | null = null;
  let cardLast4: string | null = null;
  const pmId: string | null = (typeof piPayload.payment_method === 'string' ? piPayload.payment_method : piPayload.payment_method?.id) ?? null;
  if (pmId) {
    try {
      const pm = await stripe.getPaymentMethod(pmId);
      cardBrand = pm.card?.brand ?? null;
      cardLast4 = pm.card?.last4 ?? null;
    } catch {}
  }

  const total = parseFloat(approval.amount as any);
  const currency = approval.currency;

  // Approve + execute the approval row.
  await supabase
    .from('agent_payment_approvals')
    .update({
      status: 'approved',
      decided_by: decidedBy,
      decided_at: new Date().toISOString(),
      decision_reason: 'guest checkout',
    })
    .eq('id', approval.id);

  // Insert transfer.
  const { data: transfer } = await supabase
    .from('transfers')
    .insert({
      tenant_id: approval.tenant_id,
      environment: 'test',
      from_account_id: checkout.account_id,
      to_account_id: checkout.merchant_account_id || checkout.account_id,
      amount: total,
      currency,
      type: 'acp',
      status: 'completed',
      description: `Sly guest checkout: ${checkout.merchant_name} (card ${cardBrand} ${cardLast4})`,
      protocol_metadata: {
        protocol: 'acp',
        source: 'sly_buy_guest',
        checkout_id: ctxData.checkout_id,
        merchant_id: checkout.merchant_id,
        merchant_account_id: checkout.merchant_account_id,
        merchant_name: checkout.merchant_name,
        agent_id: approval.agent_id,
        stripe_payment_intent_id: pi.id,
        stripe_payment_method: pmId,
        card_brand: cardBrand,
        card_last4: cardLast4,
        guest_checkout: true,
      },
      initiated_by_type: 'user',
      initiated_by_id: decidedBy,
      initiated_by_name: 'guest checkout',
    })
    .select()
    .single();

  await supabase
    .from('acp_checkouts')
    .update({
      status: 'completed',
      transfer_id: transfer?.id || null,
      payment_method: 'card',
      completed_at: new Date().toISOString(),
      checkout_data: {
        source: 'sly_buy_guest',
        stripe_payment_intent_id: pi.id,
        stripe_payment_status: pi.status,
        card_brand: cardBrand,
        card_last4: cardLast4,
      },
    })
    .eq('id', checkout.id);

  // Mark approval executed + persist receipt fields for idempotent reloads.
  await supabase
    .from('agent_payment_approvals')
    .update({
      status: 'executed',
      executed_transfer_id: transfer?.id || null,
      executed_at: new Date().toISOString(),
      payment_context: {
        ...ctxData,
        stripe_payment_intent_id: pi.id,
        card_brand: cardBrand,
        card_last4: cardLast4,
        merchant_name: checkout.merchant_name,
      },
    })
    .eq('id', approval.id);

  return c.json({
    status: 'completed',
    merchant: checkout.merchant_name,
    total,
    currency,
    transfer_id: transfer?.id || null,
    charge: {
      id: pi.id,
      brand: cardBrand,
      last4: cardLast4,
    },
  });
});

app.post('/:token', async (c) => {
  const token = c.req.param('token');
  return handleApproveByToken(c, token);
});

app.get('/:token', async (c) => {
  const token = c.req.param('token');
  return handleApproveByToken(c, token);
});

export default app;
